# NUMPY LESSONS

In [2]:
import numpy as np # imports the numpy library

kanto = np.array([73, 65, 78])
print(kanto)
w1 = 12
w2 = 15
w3 = 18
weight = np.array([w1, w2, w3])
print(weight)
print(type(weight))
print(type(kanto))
print(weight[1])
print(kanto[2])

np.dot(kanto, weight)

climate = np.array([[12, 13, 17],
                 [22, 24, 28],
                 [10, 9, 5],
                 [32, 30, 31],
                 [1, 5, 3]])
print(climate)
climate.dtype

[73 65 78]
[12 15 18]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
15
78
[[12 13 17]
 [22 24 28]
 [10  9  5]
 [32 30 31]
 [ 1  5  3]]


dtype('int32')

In [3]:
weight = np.array([1, 4, 7])
np.matmul(climate, weight) # 2 dimensional matrix

np.dot(climate, weight) # does the same thing as the matrix
# help(np.dot)
#help(np.var)

array([183, 314,  81, 369,  42])

In [4]:
np.add(10, 12)
np.subtract(50, 70)
np.divide(40, 8)
np.multiply(12, 12)

x1 = np.arange(9.0).reshape((3, 3)) # arange gets a range of number 0-8 and puts them in a ndarray format.
#print(x1) # reshape arranges them in a 3 rows by 3 columns 2-D array.
x2 = np.arange(3.0)
#print(x2)
np.add(x1, x2)

np.max([1, 3, 4, 8, 22, 34, 120, 29, 150, 234, 100])
numb = [1, 3, 4, 8, 22, 34, 120, 29, 150, 234, 100]
np.min(numb)
np.mean(numb)
np.median(numb)
np.sum(numb)
np.var(numb)
np.std(numb)
np.max(numb)
np.average(numb)


64.0909090909091

In [7]:
# Arithmetic operations with numpy
arr_1 = np.array([[1, 5, 4,], [8, 9, 2], [2, 10, 15]])
#print(arr_1)
arr_2 = np.array([[12, 14, 11], [0, 6, 9], [13, 20, 10]])
arr_1 + arr_2
arr_2 + 5
arr_1 * 2
arr_2 / 2
arr_2 % 2
arr_2 // 2
arr_1 - 5
arr_1.shape
arr_3 = np.array([5, 8, 4])
arr_3.shape
arr_1 + arr_3 # broadcasting with numpy
# Comparison operators with numpy
arr_1 == arr_2
arr_1 > arr_2
arr_1 < arr_2
arr_3 == arr_1
arr_2 != arr_3
(arr_1 > arr_3).sum() # To find the count of numbers that match the comparison operator, we use sum
arr_1[1, 1] # Picking arrays by their index
arr_4 = np.array([[[13, 14, 15],
                   [11, 2, 4]],
                   [[10, 11, 5],
                    [2, 5, 8]],
                    [[12, 20, 18],
                     [1, 5, 9]]])
arr_4.shape
# Array using ranges
arr_4[1:, 0:1, :2]
arr_4[1:, 1, 2] # mixing index anf range
# Other ways to create arrays
np.zeros((3,3))
np.ones((4,3))
np.zeros([5,4])
np.eye(4) # Identity matrix
np.random.rand(5) # Random vector
np.random.randn(3,4) # Random matrix
np.full([3,3],24) # creating a fixed value
np.arange(10, 74, 2).shape
np.arange(10,74,2).reshape(4,8)
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])